# Docker Compose Configuration
services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: nestpassword
      POSTGRES_DB: nestdb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nestjs-network

  # NestJS Application
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    restart: always
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - nestjs-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

# Named volumes for data persistence
volumes:
  postgres_data:
# Network for container communication
networks:
  nestjs-network:
    driver: bridge
