name: CD Pipeline

on:
  workflow_run:
    workflows: ['CI Pipeline']
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: sudo docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Pull Docker image
        run: sudo docker pull sankarkruthiventi/repo090924:latest
      - name: Delete Old docker container
        run: sudo docker rm -f repo
      - name: Pull Docker image
        run: sudo docker pull sankarkruthiventi/repo090924:latest
      - name: Delete Old docker container
        run: sudo docker rm -f repo090924-container || true
      - name: Run Docker Container
        run: |
          sudo docker run -d \
            -e NODE_ENV=production \
            -e DATABASE_HOST=${{ secrets.DATABASE_HOST }} \
            -e DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} \
            -e DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} \
            -e DATABASE_PORT=5432 \
            -e DATABASE_NAME=${{ secrets.DATABASE_NAME }} \
            -p 3000:3000 \
            --name repo090924-container \
            sankarkruthiventi/repo090924:latest
